version: '3'
services:
  db:
    image: postgres:14
    container_name: crypto_rates_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build: .
    container_name: crypto_rates_app
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: crypto_db
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
